baseURL: "https://wmadavis.com/" 
title: W. Matthew Alampay Davis
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
disablePathToLower: true

taxonomies:

    tag: tags

menu:
    main:
        - name: Vita
          url: /CV-AlampayDavis.pdf
          weight: 1  
        - name: Research
          url: /research/
          weight: 2
        - name: Teaching
          url: /teaching/
          weight: 3
        - name: Resources
          url: /resources/
          weight: 4
        - name: Contact
          url: /contact/
          weight: 5
        - name: Other
          url: /other/
          weight: 6

params:
    description: "Academic website for W. Matthew Alampay Davis"
    author: W. Matthew Alampay Davis
    DateFormat: "02 Jan 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: true
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Matthew Alampay Davis
          subtitle: "I’m a fifth-year PhD candidate at Columbia University’s department of economics. My research interests are in the political economy of development and the environment. In ongoing projects, I study the the distributional and political consequences of climate change and the transmission of gendered violence and cultural norms in the Global South."
          imageUrl: "/profile3.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Matthew Alampay Davis
          imageUrl: "/profile3.png"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Matthew Alampay Davis
          buttons:
            - name: Vita
              url: /CV-AlampayDavis.pdf
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: Resources
              url: /resources/
            - name: Contact
              url: /contact/
    socialIcons:
        - name: Email
          url: mailto:wm.alampaydavis@gmail.com
        - name: GitHub
          url: https://github.com/wmadavis?tab=repositories
        - name: Office hours
          url: https://calendly.com/wmadavis
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ri2tMA8AAAAJ
        - name: Location
          url: /contact/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Matthew Alampay Davis"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 4
        ordered: false
        startLevel: 3

# max number of characters:
# * title: 300
# * description: 120–155
# * summary: 1500
