baseURL: "https://wmadavis.com/" 
title: W. Matthew Alampay Davis
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
disablePathToLower: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Vita
          url: /CV-AlampayDavis.pdf
          weight: 1  
        - name: Research
          url: /Research/
          weight: 2
        - name: Teaching
          url: /teaching/
          weight: 3
        - name: Other
          url: /other/
          weight: 4 

params:
    description: "Academic website for W. Matthew Alampay Davis"
    author: W. Matthew Alampay Davis
    DateFormat: "2006-01-02"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Matthew Alampay Davis
          subtitle: >
                    I’m a fifth-year PhD candidate at Columbia University’s department of economics. My research interests are in the political economy of development, inequality, and the environment. In ongoing projects, I study the distributional consequences of climate change and the transmission of gendered violence and norms in the Global South.
                    Note this site is under construction as I transition to a new host and may be buggy. Many apologies to anyone who desperately needs to read my research or old lecture notes; please just hang in there, I promise they’ll be back soon.
          imageUrl: "/profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Matthew Alampay Davis
          imageUrl: "/profile.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Matthew Alampay Davis
          buttons:
            - name: Vita
              url: /CV-AlampayDavis.pdf
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: Other
              url: /other/
    socialIcons:
        - name: Email
          url: mailto:wm.alampaydavis@gmail.com
        - name: GitHub
          url: https://github.com/wmadavis?tab=repositories
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ri2tMA8AAAAJ
        - name: Twitter
          url: https://twitter.com/alampaydavis
        - name: goodreads
          url: https://www.goodreads.com/wmadavis
        - name: Office hours
          url: https://calendly.com/wmadavis
        - name: Location
          url: /location/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Matthew Alampay Davis"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
